service: hello-world
plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello-world:
    handler: handler.hello
    events:
      - http:
          path: /
          method: GET
